// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.tankDriveBot2015;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CANTalon;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Solenoid pneumaticssolenoidOne;
    public static Solenoid pneumaticssolenoidTwo;
    public static Solenoid pneumaticssolenoidThree;
    public static Solenoid pneumaticssolenoidFour;
    public static Solenoid pneumaticssolenoidFive;
    public static Solenoid pneumaticssolenoidSix;
    public static Solenoid pneumaticssolenoidSeven;
    public static Solenoid pneumaticssolenoidEight;
    public static CANTalon driveTrainleftFront;
    public static CANTalon driveTrainleftBack;
    public static CANTalon driveTrainrightFront;
    public static CANTalon driveTrainrightBack;
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        pneumaticssolenoidOne = new Solenoid(0, 0);
        LiveWindow.addActuator("Pneumatics", "solenoidOne", pneumaticssolenoidOne);
        
        pneumaticssolenoidTwo = new Solenoid(0, 1);
        LiveWindow.addActuator("Pneumatics", "solenoidTwo", pneumaticssolenoidTwo);
        
        pneumaticssolenoidThree = new Solenoid(0, 2);
        LiveWindow.addActuator("Pneumatics", "solenoidThree", pneumaticssolenoidThree);
        
        pneumaticssolenoidFour = new Solenoid(0, 3);
        LiveWindow.addActuator("Pneumatics", "solenoidFour", pneumaticssolenoidFour);
        
        pneumaticssolenoidFive = new Solenoid(0, 4);
        LiveWindow.addActuator("Pneumatics", "solenoidFive", pneumaticssolenoidFive);
        
        pneumaticssolenoidSix = new Solenoid(0, 5);
        LiveWindow.addActuator("Pneumatics", "solenoidSix", pneumaticssolenoidSix);
        
        pneumaticssolenoidSeven = new Solenoid(0, 6);
        LiveWindow.addActuator("Pneumatics", "solenoidSeven", pneumaticssolenoidSeven);
        
        pneumaticssolenoidEight = new Solenoid(0, 7);
        LiveWindow.addActuator("Pneumatics", "solenoidEight", pneumaticssolenoidEight);
        
        driveTrainleftFront = new CANTalon(2);
        
        
        driveTrainleftBack = new CANTalon(3);
        
        
        driveTrainrightFront = new CANTalon(4);
        
        
        driveTrainrightBack = new CANTalon(5);
        
        
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
