// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.tankDriveBot2015;
    
import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.CANTalon;

import edu.wpi.first.wpilibj.livewindow.LiveWindow;
import java.util.Vector;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static Solenoid testPistonSubsystemtestCompressorSolenoid;
    public static Solenoid testPistonSubsystemtestExhaustSolenoid;
    public static DigitalInput testPistonSubsystemtestMag;
    public static DoubleSolenoid pneumaticsdoubleSolenoidOne;
    public static DoubleSolenoid pneumaticsdoubleSolenoidTwo;
    public static Solenoid pneumaticssolenoidOne;
    public static Solenoid pneumaticssolenoidTwo;
    public static CANTalon driveTrainleftFront;
    public static CANTalon driveTrainleftBack;
    public static CANTalon driveTrainrightFront;
    public static CANTalon driveTrainrightBack;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        testPistonSubsystemtestCompressorSolenoid = new Solenoid(1, 7);
        LiveWindow.addActuator("TestPistonSubsystem", "testCompressorSolenoid", testPistonSubsystemtestCompressorSolenoid);
        
        testPistonSubsystemtestExhaustSolenoid = new Solenoid(1, 6);
        LiveWindow.addActuator("TestPistonSubsystem", "testExhaustSolenoid", testPistonSubsystemtestExhaustSolenoid);
        
        testPistonSubsystemtestMag = new DigitalInput(9);
        LiveWindow.addSensor("TestPistonSubsystem", "testMag", testPistonSubsystemtestMag);
        
        pneumaticsdoubleSolenoidOne = new DoubleSolenoid(1, 2, 0);      
        LiveWindow.addActuator("Pneumatics", "doubleSolenoidOne", pneumaticsdoubleSolenoidOne);
        
        pneumaticsdoubleSolenoidTwo = new DoubleSolenoid(1, 3, 5);      
        LiveWindow.addActuator("Pneumatics", "doubleSolenoidTwo", pneumaticsdoubleSolenoidTwo);
        
        pneumaticssolenoidOne = new Solenoid(1, 1);
        LiveWindow.addActuator("Pneumatics", "solenoidOne", pneumaticssolenoidOne);
        
        pneumaticssolenoidTwo = new Solenoid(1, 4);
        LiveWindow.addActuator("Pneumatics", "solenoidTwo", pneumaticssolenoidTwo);
        
        driveTrainleftFront = new CANTalon(2);
        
        
        driveTrainleftBack = new CANTalon(3);
        
        
        driveTrainrightFront = new CANTalon(4);
        
        
        driveTrainrightBack = new CANTalon(5);
        
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
