// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.tankDriveBot2015.subsystems;

import org.usfirst.frc1073.tankDriveBot2015.Robot;
import org.usfirst.frc1073.tankDriveBot2015.RobotMap;
import org.usfirst.frc1073.tankDriveBot2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class Pneumatics extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DoubleSolenoid doubleSolenoidOne = RobotMap.pneumaticsdoubleSolenoidOne;
    DoubleSolenoid doubleSolenoidTwo = RobotMap.pneumaticsdoubleSolenoidTwo;
    Solenoid solenoidOne = RobotMap.pneumaticssolenoidOne;
    Solenoid solenoidTwo = RobotMap.pneumaticssolenoidTwo;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    /* 
     * Solenoids One and Two are going to be used for the commands raiseElevator and lowerElevator
     * Solendoids Three and Four are going to be used for the commands extendArms and retractArms
     * Solendoids Five and Six are going to be used for the commands extendClaws and retractClaws
     * Solenoids Seven and Eight are going to be used for the commands extendHooks and retractHooks
     */
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void setAllClosed(){
    	doubleSolenoidOne.set(Value.kOff);
    	doubleSolenoidTwo.set(Value.kOff);
    	solenoidOne.set(false);
    	solenoidTwo.set(false);
    	Robot.testPistonSubsystem.testCompressorSolenoid.set(true);
    	Robot.testPistonSubsystem.testExhaustSolenoid.set(false);
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

