// RobotBuilder Version: 1.5
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1073.tankDriveBot2015.subsystems;

import org.usfirst.frc1073.tankDriveBot2015.RobotMap;
import org.usfirst.frc1073.tankDriveBot2015.commands.*;

import edu.wpi.first.wpilibj.*;
import edu.wpi.first.wpilibj.DoubleSolenoid.Value;
import edu.wpi.first.wpilibj.command.Subsystem;


/**
 *
 */
public class TestPistonSubsystem extends Subsystem {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    DigitalInput testMag = RobotMap.testPistonSubsystemtestMag;
    DoubleSolenoid testPistonDoubleSolenoid = RobotMap.testPistonSubsystemtestPistonDoubleSolenoid;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    private boolean wasPassed = false;
    
    // Put methods for controlling this subsystem
    // here. Call these from Commands.
    
    public void testThePiston(){
    	
    	if(!testMag.get() && !wasPassed){
    		if(testMag.get()) wasPassed = true;
    		testPistonDoubleSolenoid.set(Value.kForward);
    	}
    	else testPistonDoubleSolenoid.set(Value.kOff);
    	
    }
    
    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND
	
        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }
}

